---

plugins:
  - import

env:
  node: true
  es6: true
  browser: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0

ignorePatterns: ["/dist"]